wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [25, 40, 30]
    rows: [13, 13]
  refreshInterval: 1
  mods:
    gcal:
      colors:
        title: "orange"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "evantypanski@gmail.com"
      enabled: true
      eventCount: 12
      position:
        top: 0
        left: 2
        height: 2
        width: 1
      refreshInterval: 300
      secretFile: "~/.wtf/gcal/client_secret.json"
      withLocation: true
    weather:
      # From http://openweathermap.org/help/city_list.txt
      cityids:
      - 4752031
      - 4758023
      colors:
        current: "lightblue"
      enabled: true
      language: "EN"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 900
      tempUnit: "F"
    git:
      commitCount: 10
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 8
      repositories:
      - "/home/evan/src/personal/sites/personal_site_4/"
    github:
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 300
      repositories:
        design: "WebAssembly"
      username: "evantypanski"
