[[manager.prepend_keymap]]
on = ["F"]
run = "plugin fg --args='ag'"
desc = "ag"

[[manager.prepend_keymap]]
on = ["<C-f>"]
run = "plugin fg --args='fzf'"
desc = "fzf"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
